this["JST"] = this["JST"] || {};

this["JST"]["templates/logic/LoginTemplate.hbs"] = Handlebars.template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Handlebars.helpers); data = data || {};
  var buffer = "", stack1, functionType="function", escapeExpression=this.escapeExpression;


  buffer += "<div class=\"wrapperFixed wrapper-primaryImage\">\r\n    <div class=\"frame\">\r\n        <div class=\"gapTop-primary smallPanel\">\r\n            <div class=\"well\">\r\n                <form novalidate=\"novalidate\"  id=\"js-login-form\" class=\"form-horizontal\">\r\n                    <h2 class=\"hd hd_3 text-center\">";
  if (stack1 = helpers.title) { stack1 = stack1.call(depth0, {hash:{},data:data}); }
  else { stack1 = depth0.title; stack1 = typeof stack1 === functionType ? stack1.apply(depth0) : stack1; }
  buffer += escapeExpression(stack1)
    + "</h2>\r\n                    <div class=\"control-group\">\r\n                        <input class=\"required\" type=\"email\" placeholder=\"Email\" name=\"emailAddress\" value=\"\">\r\n                    </div>\r\n                    <div class=\"control-group\">\r\n                        <input class=\"required\" type=\"password\" placeholder=\"Password\" name=\"password\" value=\"\">\r\n                    </div>\r\n                    <div class=\"control-group\">\r\n                        <button id=\"js-login-btn\" type=\"submit\" class=\"btn btn-primary\">Sign in</button>\r\n                    </div>\r\n                    <p><a href=\"#\" class=\"online-only\">Forgot your password?</a></p>\r\n                </form>\r\n            </div>\r\n            <!-- /well -->\r\n        </div>\r\n        <!-- /gapTop-primary -->\r\n    </div>\r\n    <!-- /frame -->\r\n</div>\r\n<!-- /wrapperBackground -->";
  return buffer;
  });

this["JST"]["templates/topbar/TopNavigationTemplate.hbs"] = Handlebars.template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Handlebars.helpers); data = data || {};
  


  return "<div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n    <div class=\"navbar-inner\">\r\n        <div class=\"frame frame_header\">\r\n            <h1 id=\"js-page-title\" class=\"hd-page\"></h1>\r\n            <a class=\"brand\" href=\"\"><i class=\"icon-logo\">The</i> App</a>\r\n            <div class=\"nav-collapse collapse\">\r\n                <div class=\"pull-right\">\r\n                    <ul class=\"nav pull-right\">\r\n                        <li>\r\n                            <span id=\"js-online-status\" class=\"label label-header label-success\">Online</span>\r\n                        </li>\r\n                        <li id=\"js-user-dropdown\" class=\"dropdown\">\r\n                            <a href=\"javascript:void(0);\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><span id=\"js-user-name\">Welcome</span> <b class=\"caret\"></b></a>\r\n                            <ul class=\"dropdown-menu\">\r\n                                <li>\r\n                                    <a id=\"js-edit-profile-link\" class=\"online-only\" href=\"\"><i  class=\"icon-edit\"></i> Edit Profile</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a id=\"js-user-link\" class=\"online-only\" href=\"\"><i class=\"icon-user\"></i> User Administration</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a id=\"js-dealer-link\" class=\"online-only\" href=\"\"><i class=\"icon-globe\"></i> Partner Management</a>\r\n                                </li>\r\n                                <li>\r\n                                    <a id=\"js-invite-link\" class=\"online-only\" href=\"\"><i class=\"icon-envelope\"></i> Invite User</a>\r\n                                </li>\r\n                                <li class=\"divider\"></li>\r\n                                <li>\r\n                                    <a id=\"js-log-off\" href=\"\"><i class=\"icon-off\"></i> Sign Out</a>\r\n                                </li>\r\n                            </ul>\r\n                        </li>\r\n                    </ul>\r\n                    <!-- /nav -->\r\n                </div>\r\n                <!-- /pull-right -->\r\n            </div>\r\n            <!-- /nav-collapse -->\r\n        </div>\r\n        <!-- /container -->\r\n    </div>\r\n    <!-- /navbar-inner -->\r\n</div>\r\n<!-- /navbar -->";
  });